CREATE TABLE `golf_registrations` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `billing_name` text NOT NULL,
 `billing_email` text NOT NULL,
 `billing_phone` text NOT NULL,
 `billing_address` text NOT NULL,
 `billing_amount` int(11) NOT NULL,
 `player1_name` text NOT NULL,
 `player1_email` text NOT NULL,
 `player1_phone` text NOT NULL,
 `player1_graduated` text NOT NULL,
 `player1_shirt` text NOT NULL,
 `player2_name` text NOT NULL,
 `player2_email` text NOT NULL,
 `player2_phone` text NOT NULL,
 `player2_graduated` text NOT NULL,
 `player2_shirt` text NOT NULL,
 `player3_name` text NOT NULL,
 `player3_email` text NOT NULL,
 `player3_phone` text NOT NULL,
 `player3_graduated` text NOT NULL,
 `player3_shirt` text NOT NULL,
 `player4_name` text NOT NULL,
 `player4_email` text NOT NULL,
 `player4_phone` text NOT NULL,
 `player4_graduated` text NOT NULL,
 `player4_shirt` text NOT NULL,
 `stripe_transaction` text NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;